yolobid/urls.py
from __future__ import unicode_literals

from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin

from mezzanine.core.views import direct_to_template
from mezzanine.conf import settings


admin.autodiscover()

# Add the urlpatterns for any custom Django applications here.
# You can also change the ``home`` view to add your own functionality
# to the project's homepage.

urlpatterns = i18n_patterns("",
    # Change the admin prefix here to use an alternate URL for the
    # admin interface, which would be marginally more secure.
    ("^admin/", include(admin.site.urls)),
)

if settings.USE_MODELTRANSLATION:
    urlpatterns += patterns('',
        url('^i18n/$', 'django.views.i18n.set_language', name='set_language'),
    )

urlpatterns += patterns('',
    # We don't want to presume how your homepage works, so here are a
    # few patterns you can use to set it up.

    # HOMEPAGE AS STATIC TEMPLATE
    # ---------------------------
    # This pattern simply loads the index.html template. It isn't
    # commented out like the others, so it's the default. You only need
    # one homepage pattern, so if you use a different one, comment this
    # one out.

    url("^$", direct_to_template, {"template": "index.html"}, name="home"),
    url(r'^', include('dashboard.urls', namespace="dashboard")),
    # HOMEPAGE AS AN EDITABLE PAGE IN THE PAGE TREE
    # ---------------------------------------------
    # This pattern gives us a normal ``Page`` object, so that your
    # homepage can be managed via the page tree in the admin. If you
    # use this pattern, you'll need to create a page in the page tree,
    # and specify its URL (in the Meta Data section) as "/", which
    # is the value used below in the ``{"slug": "/"}`` part.
    # Also note that the normal rule of adding a custom
    # template per page with the template name using the page's slug
    # doesn't apply here, since we can't have a template called
    # "/.html" - so for this case, the template "pages/index.html"
    # should be used if you want to customize the homepage's template.

    # url("^$", "mezzanine.pages.views.page", {"slug": "/"}, name="home"),

    # HOMEPAGE FOR A BLOG-ONLY SITE
    # -----------------------------
    # This pattern points the homepage to the blog post listing page,
    # and is useful for sites that are primarily blogs. If you use this
    # pattern, you'll also need to set BLOG_SLUG = "" in your
    # ``settings.py`` module, and delete the blog page object from the
    # page tree in the admin if it was installed.

    # url("^$", "mezzanine.blog.views.blog_post_list", name="home"),

    # MEZZANINE'S URLS
    # ----------------
    # ADD YOUR OWN URLPATTERNS *ABOVE* THE LINE BELOW.
    # ``mezzanine.urls`` INCLUDES A *CATCH ALL* PATTERN
    # FOR PAGES, SO URLPATTERNS ADDED BELOW ``mezzanine.urls``
    # WILL NEVER BE MATCHED!

    # If you'd like more granular control over the patterns in
    # ``mezzanine.urls``, go right ahead and take the parts you want
    # from it, and use them directly below instead of using
    # ``mezzanine.urls``.
    ("^", include("mezzanine.urls")),


    # MOUNTING MEZZANINE UNDER A PREFIX
    # ---------------------------------
    # You can also mount all of Mezzanine's urlpatterns under a
    # URL prefix if desired. When doing this, you need to define the
    # ``SITE_PREFIX`` setting, which will contain the prefix. Eg:
    # SITE_PREFIX = "my/site/prefix"
    # For convenience, and to avoid repeating the prefix, use the
    # commented out pattern below (commenting out the one above of course)
    # which will make use of the ``SITE_PREFIX`` setting. Make sure to
    # add the import ``from django.conf import settings`` to the top
    # of this file as well.
    # Note that for any of the various homepage patterns above, you'll
    # need to use the ``SITE_PREFIX`` setting as well.

    # ("^%s/" % settings.SITE_PREFIX, include("mezzanine.urls"))

)

# Adds ``STATIC_URL`` to the context of error pages, so that error
# pages can use JS, CSS and images.
handler404 = "mezzanine.core.views.page_not_found"
handler500 = "mezzanine.core.views.server_error"

dashboard/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
#
# Also note: You'll have to insert the output of 'django-admin sqlcustom [app_label]'
# into your database.
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone


class DataSource(models.Model):
    created_date = models.DateTimeField(blank=True, null=True)
    name = models.CharField(max_length=255, blank=True, null=True)
    external_location = models.CharField(max_length=255, blank=True, null=True)
    tournament = models.ForeignKey('Tournament', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'data_source'


class Game(models.Model):
    created_date = models.DateTimeField(blank=True, null=True)
    game_length_minutes = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    external_id = models.IntegerField(blank=True, null=True)
    data_source = models.ForeignKey(DataSource, blank=True, null=True)
    tournament = models.ForeignKey('Tournament', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'game'


class Player(models.Model):
    created_date = models.DateTimeField(blank=True, null=True)
    name = models.CharField(max_length=255, blank=True, null=True)
    # role = models.CharField(max_length=255, blank=True, null=True)
    # image = models.CharField(max_length=255, blank=True, null=True)
    external_id = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'player'


class PlayerStats(models.Model):
    created_date = models.DateTimeField(blank=True, null=True)
    champion_played = models.CharField(max_length=255, blank=True, null=True)
    kills = models.IntegerField(blank=True, null=True)
    deaths = models.IntegerField(blank=True, null=True)
    assists = models.IntegerField(blank=True, null=True)
    gold = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    minions_killed = models.IntegerField(blank=True, null=True)
    game = models.ForeignKey(Game, blank=True, null=True)
    team = models.ForeignKey('Team', blank=True, null=True)
    player = models.ForeignKey(Player, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'player_stats'


class PlayerStatsDf(models.Model):
    index = models.BigIntegerField(blank=True, null=True)
    assists = models.BigIntegerField(blank=True, null=True)
    champion_played = models.TextField(blank=True, null=True)
    created_date = models.DateTimeField(blank=True, null=True)
    deaths = models.BigIntegerField(blank=True, null=True)
    game_id = models.BigIntegerField(blank=True, null=True)
    game_length_minutes = models.FloatField(blank=True, null=True)
    gold = models.FloatField(blank=True, null=True)
    id = models.BigIntegerField(blank=True, primary_key=True)
    kills = models.BigIntegerField(blank=True, null=True)
    minions_killed = models.BigIntegerField(blank=True, null=True)
    player_id = models.BigIntegerField(blank=True, null=True)
    player_name = models.TextField(blank=True, null=True)
    team_id = models.BigIntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'player_stats_df'


class ProcessedPlayerStatsDf(models.Model):
    index = models.BigIntegerField(blank=True, null=True)
    assists = models.BigIntegerField(blank=True, null=True)
    champion_played = models.TextField(blank=True, null=True)
    created_date = models.DateTimeField(blank=True, null=True)
    deaths = models.BigIntegerField(blank=True, null=True)
    game = models.ForeignKey(Game, blank=True, null=True)
    game_length_minutes = models.FloatField(blank=True, null=True)
    gold = models.FloatField(blank=True, null=True)
    id = models.BigIntegerField(blank=True, primary_key=True)
    kills = models.BigIntegerField(blank=True, null=True)
    minions_killed = models.BigIntegerField(blank=True, null=True)
    player_id = models.BigIntegerField(blank=True, null=True)
    player_name = models.TextField(blank=True, null=True)
    # team = models.ForeignKey('Team', blank=True, null=True)
    csum_game_length_minutes = models.FloatField(blank=True, null=True)
    csum_prev_game_length_minutes = models.FloatField(blank=True, null=True)
    per_min_game_length_minutes = models.FloatField(blank=True, null=True)
    csum_kills = models.BigIntegerField(blank=True, null=True)
    csum_prev_kills = models.BigIntegerField(blank=True, null=True)
    per_min_kills = models.FloatField(blank=True, null=True)
    csum_min_kills = models.FloatField(blank=True, null=True)
    csum_prev_min_kills = models.FloatField(blank=True, null=True)
    csum_deaths = models.BigIntegerField(blank=True, null=True)
    csum_prev_deaths = models.BigIntegerField(blank=True, null=True)
    per_min_deaths = models.FloatField(blank=True, null=True)
    csum_min_deaths = models.FloatField(blank=True, null=True)
    csum_prev_min_deaths = models.FloatField(blank=True, null=True)
    csum_assists = models.BigIntegerField(blank=True, null=True)
    csum_prev_assists = models.BigIntegerField(blank=True, null=True)
    per_min_assists = models.FloatField(blank=True, null=True)
    csum_min_assists = models.FloatField(blank=True, null=True)
    csum_prev_min_assists = models.FloatField(blank=True, null=True)
    csum_minions_killed = models.BigIntegerField(blank=True, null=True)
    csum_prev_minions_killed = models.BigIntegerField(blank=True, null=True)
    per_min_minions_killed = models.FloatField(blank=True, null=True)
    csum_min_minions_killed = models.FloatField(blank=True, null=True)
    csum_prev_min_minions_killed = models.FloatField(blank=True, null=True)
    csum_gold = models.FloatField(blank=True, null=True)
    csum_prev_gold = models.FloatField(blank=True, null=True)
    per_min_gold = models.FloatField(blank=True, null=True)
    csum_min_gold = models.FloatField(blank=True, null=True)
    csum_prev_min_gold = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'processed_player_stats_df'


class ProcessedTeamStatsDf(models.Model):
    index = models.BigIntegerField(blank=True, null=True)
    allowed_assists = models.BigIntegerField(blank=True, null=True)
    allowed_deaths = models.BigIntegerField(blank=True, null=True)
    allowed_gold = models.BigIntegerField(blank=True, null=True)
    allowed_kills = models.BigIntegerField(blank=True, null=True)
    allowed_minions_killed = models.BigIntegerField(blank=True, null=True)
    assists = models.BigIntegerField(blank=True, null=True)
    barons = models.BigIntegerField(blank=True, null=True)
    color = models.TextField(blank=True, null=True)
    created_date = models.DateTimeField(blank=True, null=True)
    deaths = models.BigIntegerField(blank=True, null=True)
    dragons = models.BigIntegerField(blank=True, null=True)
    game = models.ForeignKey(Game, blank=True, null=True)
    game_length_minutes = models.FloatField(blank=True, null=True)
    game_number = models.BigIntegerField(blank=True, null=True)
    gold = models.BigIntegerField(blank=True, null=True)
    id = models.BigIntegerField(primary_key=True)
    kills = models.BigIntegerField(blank=True, null=True)
    minions_killed = models.BigIntegerField(blank=True, null=True)
    team = models.ForeignKey('Team', blank=True, null=True)
    team_name = models.TextField(blank=True, null=True)
    total_gold = models.TextField(blank=True, null=True)
    turrets = models.BigIntegerField(blank=True, null=True)
    won = models.NullBooleanField()
    clean_kills = models.BigIntegerField(blank=True, null=True)
    allowed_clean_kills = models.BigIntegerField(blank=True, null=True)
    k_a = models.BigIntegerField(blank=True, null=True)
    a_over_k = models.FloatField(blank=True, null=True)
    allowed_k_a = models.BigIntegerField(blank=True, null=True)
    allowed_a_over_k = models.FloatField(blank=True, null=True)
    allowed_assists_for_game = models.BigIntegerField(blank=True, null=True)
    allowed_deaths_for_game = models.BigIntegerField(blank=True, null=True)
    allowed_gold_for_game = models.BigIntegerField(blank=True, null=True)
    allowed_kills_for_game = models.BigIntegerField(blank=True, null=True)
    allowed_minions_killed_for_game = models.BigIntegerField(blank=True, null=True)
    assists_for_game = models.BigIntegerField(blank=True, null=True)
    barons_for_game = models.BigIntegerField(blank=True, null=True)
    deaths_for_game = models.BigIntegerField(blank=True, null=True)
    dragons_for_game = models.BigIntegerField(blank=True, null=True)
    game_length_minutes_for_game = models.FloatField(blank=True, null=True)
    game_number_for_game = models.BigIntegerField(blank=True, null=True)
    gold_for_game = models.BigIntegerField(blank=True, null=True)
    id_for_game = models.BigIntegerField(blank=True, null=True)
    kills_for_game = models.BigIntegerField(blank=True, null=True)
    minions_killed_for_game = models.BigIntegerField(blank=True, null=True)
    team_id_for_game = models.BigIntegerField(blank=True, null=True)
    turrets_for_game = models.BigIntegerField(blank=True, null=True)
    won_for_game = models.NullBooleanField()
    clean_kills_for_game = models.BigIntegerField(blank=True, null=True)
    allowed_clean_kills_for_game = models.BigIntegerField(blank=True, null=True)
    k_a_for_game = models.BigIntegerField(blank=True, null=True)
    a_over_k_for_game = models.FloatField(blank=True, null=True)
    allowed_k_a_for_game = models.BigIntegerField(blank=True, null=True)

moderna/models.py
from django.db import models

# Create your models here.

moderna/views.py
from django.shortcuts import render

# Create your views here.

moderna/templates/generic/includes/comment.html
{% load i18n mezzanine_tags comment_tags rating_tags %}

{% for comment in comments_for_thread %}

<div id="comment-{{ comment.id }}"
    class="comment media{% if comment.by_author %} comment-author{% endif %}">

    {% editable comment.is_public comment.is_removed %}
    {% if not comment.is_removed and comment.is_public or request.user.is_staff %}
    {% if comment.url %}
    <a href="{{ comment.url }}">
        <img class="pull-left media-object" src="{% gravatar_url comment.email %}">
    </a>
    <div class="media-body">
        <h4 class="media-heading"><a href="{{ comment.url }}">{{ comment.user_name }}</a>
    {% else %}
    <img class="pull-left media-object" src="{% gravatar_url comment.email %}">
    <div class="media-body">
        <h4 class="media-heading">{{ comment.user_name }}
    {% endif %}
            <small class="timespan">
                {% blocktrans with sometime=comment.submit_date|timesince %}{{ sometime }} ago{% endblocktrans %}
            </small>
        </h4>
    <p>{{ comment.comment|comment_filter }}</p>
    {% endif %}
    
    {% if not comment.is_removed and comment.is_public %}
    <a href="{{ request.path }}#comment-{{ comment.id }}">
        <span class="glyphicon glyphicon-link"></span> {% trans "Link" %}
    </a> |
    <a href="#reply-{{ comment.id }}" class="reply">
        <span class="glyphicon glyphicon-share-alt"></span> {% trans "Reply" %}
    </a>
    {% if settings.COMMENTS_USE_RATINGS %}
    <div class="rating">
    {% rating_for comment %}
    </div>
    {% endif %}
    <form class="comment-reply-form" method="post" id="reply-{{ comment.id }}"
        action="{{ comment_url }}#reply-{{ comment.id }}"
        {% if replied_to != comment.id %}style="display:none;"{% endif %}>
        {% if replied_to == comment.id %}
        {% fields_for posted_comment_form %}
        {% else %}
        {% fields_for unposted_comment_form %}
        {% endif %}
        <input type="hidden" name="replied_to" value="{{ comment.id }}">
        <input class="btn btn-primary btn-lg" type="submit" value="{% trans "Reply" %}">
    </form>

    {% else %}
    <p>
        {% if comment.is_removed %}
        <span class="glyphicon glyphicon-remove-circle"></span> {% trans "Comment deleted" %}
        {% else %}
        <span class="glyphicon glyphicon-warning-sign"></span> {% trans "Comment awaiting approval" %}
        {% endif %}
        <small class="timespan">{% blocktrans with sometime=comment.submit_date|timesince %}{{ sometime }} ago{% endblocktrans %}</small>
    </p>
    {% endif %}

    {% comment_thread comment %}
    
    {% if not comment.is_removed and comment.is_public or request.user.is_staff %}</div>{% endif %}
    {% endeditable %}
</div>
{% endfor %}

{% if no_comments %}
<p>{% trans "There are currently no comments" %}</p>
{% endif %}

moderna/templates/generic/includes/comment_form.html
{% load i18n mezzanine_tags comment_tags %}

<form method="post" id="contactform" action="{{ comment_url }}#comment">
   
	{% for hidden in comment_form.hidden_fields %}
    {{ hidden }}
    {% endfor %}
    <div class="row">
		<div class="col-lg-4 field">
			 <input type="text" value="{{comment_form.name.value}}" name="name" maxlength="50" id="id_name" class="" placeholder="* Enter your full name" >
			  
		</div>
		<div class="col-lg-4 field">
			 <input type="email" value="{{comment_form.email.value}}" name="email" id="id_email" placeholder="* Enter your email address">
			
		</div>
		<div class="col-lg-4 field">
			 <input type="url" value="b''" name="{{comment_form.url.value}}" id="id_url" placeholder="Enter your webiste">
			
		</div>
		<div class="col-lg-12 margintop10 field">
			 <textarea rows="10" name="comment" id="id_comment" cols="40" class="" placeholder="* Enter Comment here..."></textarea>
			
		<p>
			<button type="submit" class="btn btn-theme margintop10 pull-left">{% trans "Comment" %}</button>
				<span class="pull-right margintop20">* Please fill all required form field, thanks!</span>
		</p>	
		</div>
		
	
	</div>
</form>

moderna/templates/generic/includes/comments.html
{% load i18n mezzanine_tags comment_tags %}
<div id="comments">
<h3>{% trans "Comments" %}</h3>
{% if settings.COMMENTS_DISQUS_SHORTNAME %}
{% include "generic/includes/disqus_comments.html" %}
{% else %}
<script>
$(function() {
    $('.reply').click(function() {
        $('.comment-reply-form').hide();
        $(this).siblings('.comment-reply-form').toggle();
    });
});
</script>
<style>.input_id_honeypot {display:none !important;}</style>
{% comment_thread object_for_comments %}
<h3>{% trans "New Comment" %}</h3>

    {% if not request.POST.replied_to %}
		{% include "generic/includes/comment_form.html" with comment_form=posted_comment_form %}
    {% else %}
    {{% include "generic/includes/comment_form.html" with comment_form=unposted_comment_form %}
    {% endif %}
    

{% endif %}
</div>

moderna/templates/generic/includes/disqus_comments.html
{% load disqus_tags %}

<div id="disqus_thread"></div>
{% disqus_sso_script %}
<script>
    var disqus_developer = '{{ settings.DEV_SERVER }}' == 'True';
    var disqus_url = 'http{% if request.is_secure %}s{% endif %}://{{ request.META.HTTP_HOST }}{{ object_for_comments.get_absolute_url }}';
    var disqus_title = '{{ object_for_comments|escapejs }}';
    var disqus_identifier = '{% disqus_id_for object_for_comments %}';
  (function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = 'http{% if request.is_secure %}s{% endif %}://{{ settings.COMMENTS_DISQUS_SHORTNAME }}.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script>

moderna/templates/generic/includes/disqus_counts.html
<script>
/* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
var disqus_shortname = '{{ settings.COMMENTS_DISQUS_SHORTNAME }}'; // required: replace example with your forum shortname

/* * * DON'T EDIT BELOW THIS LINE * * */
(function () {
    var s = document.createElement('script'); s.async = true;
    s.type = 'text/javascript';
    s.src = '//' + disqus_shortname + '.disqus.com/count.js';
    (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script>

moderna/templates/generic/includes/disqus_sso.html
<script>
var disqus_config = function () {
    this.page.remote_auth_s3 = '{{ sso_data }}';
    this.page.api_key = '{{ public_key }}';
}
</script>

moderna/templates/generic/includes/rating.html
{% load mezzanine_tags rating_tags i18n future %}

<span id="rating-{{ rating_object.id }}">
    {% if rating_average %}
    {% trans "Current rating" %}: {{ rating_average|floatformat }}
    {% else %}
    {% trans "Currently unrated" %}
    {% endif %}
</span>

{% if not rated or request.user.is_authenticated %}
<form class="form-inline" role="form" method="post" action="{% url "rating" %}">
    {% nevercache %}
    {% csrf_token %}
    {% endnevercache %}
    <ul class="radio radio-inline">{{ rating_form.as_ul }}</ul>
    <input type="submit" class="btn btn-default btn-sm" value="{% trans "Rate" %}"
        onclick="return $(this.form).find('input:checked').length == 1;">
</form>
{% endif %}